// This file contains placeholder data that you'll be replacing with real data in the Data Fetching chapter:

// https://nextjs.org/learn/dashboard-app/fetching-data
const users = [
  {
    id: '410544b2-4001-4271-9855-fec4b6a6442a',
    name: 'User',
    email: 'user@nextmail.com',
    twitter_id: 'kiikey4',
    password: '123456',
  },
];

const post_tags = [
  {
    name: 'Game Design',
  },
  {
    name: 'Game Dev General',
  },
  {
    name: 'UE5',
  },
  {
    name: 'UE / Beginner',
  },
  {
    name: 'UE / Audio',
  },
  {
    name: 'UE / C++',
  },
  {
    name: 'UE / Blueprint',
  },
  {
    name: 'UE / Animation',
  },
  {
    name: 'UE / Sequencer',
  },
  {
    name: 'UE / Environment',
  },
  {
    name: 'UE / Visual Effect',
  },
  {
    name: 'UE / Debug',
  },
  {
    name: 'UE / Localization',
  },
  {
    name: 'UE / Editor',
  },
  {
    name: 'UE / AI',
  },
  {
    name: 'UE / Rendering',
  },
  {
    name: 'UE / Lighting',
  },
  {
    name: 'UE / Material',
  },
  {
    name: 'UE / UMG',
  },
  {
    name: 'UE / Optimization',
  },
  {
    name: 'UE / Plugin',
  },
  {
    name: 'UE / Tips',
  },
  {
    name: 'Rider',
  },
  {
    name: 'Unity',
  },
  {
    name: 'Web Dev',
  },
  {
    name: 'Web / Nextjs',
  },
  {
    name: 'Other',
  },
];

const comments = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a64420',
    post_id: '3958dc9e-712f-4377-85e9-fec4b6a6442b',
    user_name: 'trollguy87',
    user_img: '/viewers/trollguy87.png',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos possimus porro earum dolor sint fuga laborum velit laudantium distinctio quos sunt veritatis unde inventore, autem ad tenetur voluptatibus mollitia vel!',
    create_date: '2022-12-06',
    modify_date: '2022-12-07',
    likes: [],
  },
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a64430',
    post_id: '3958dc9e-712f-4377-85e9-fec4b6a6442b',
    user_name: 'trollguy87',
    user_img: '/viewers/trollguy87.png',
    content: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos possimus porro earum dolor sint fuga laborum velit laudantium distinctio quos sunt veritatis unde inventore, autem ad tenetur voluptatibus mollitia vel!',
    create_date: '2023-12-06',
    modify_date: '2022-12-06',
    likes: [],
  },
]

const notifications = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a64420',
    user_name: 'trollguy87',
    post_id: '3958dc9e-712f-4377-85e9-fec4b6a64420',
    create_date: '2022-12-06',
    isRead: false,
  },
]


const posts_en = [
  {
    id: '3958dc9e-712f-4377-85e9-fec4b6a6442b',
    title: 'Example Post 1',
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['UE', 'Other'],
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    author: 'Key',
    comment_id_list: ['3958dc9e-712f-4377-85e9-fec4b6a64420', '3958dc9e-712f-4377-85e9-fec4b6a64430'],
    create_date: '2022-12-06',
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: '86b93c2d-9d95-4c14-b05f-6e7e4e167c44',
    title: 'Example Post 2',
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['Game Design', 'Game Dev General'],
    content: '# Markdown  \n## Markdown  \n### Markdown  \n#### Markdown  \n##### Markdown  \n###### Markdown  \n\n**Bold**  \n*Italic*  \n~~Strikethrough~~  \n\n1. First item  \n2. Second item  \n3. Third item  \n\n- Unordered item  \n- Unordered item  \n- Unordered item  \n\n[Link](https://www.example.com)  \n\n![Image](https://cdn.vox-cdn.com/thumbor/6z9EcmyiAJ00A_eP5tk2DmVeYe0=/0x15:500x348/1200x800/filters:focal(0x15:500x348):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/36992002/tumblr_lmwsamrrxT1qagx30.0.0.gif) \n\n![Image](https://static.zenn.studio/images/drawing/discussion.png)  \n\n```javascript  \nconsole.log("Hello, World!");  \n```  \n\n```cpp \nint main() { \n  int y = 5 + 6; \n cout << "Hellow World! " << x << std::endl();\n} \n```  \n\n> Blockquote  \n\n---  \n\n- [ ] Task 1  \n- [x] Task 2  \n\n---  \n\n| Header 1 | Header 2 |  \n| -------- | -------- |  \n| Data 1   | Data 2   |  \n\n---  \n\n<details>  \n<summary>Details</summary>  \nDetails content  \n</details>',
    author: 'Key',
    comment_id_list: [],
    create_date: '2022-12-06',
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: 'e4189b55-9232-4e56-97ec-3d67bf7351d5',
    title: 'Example Post 3',
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['UE5', 'UE / Beginner'],
    content: '<video src="https://player.cloudinary.com/embed/?public_id=v1624176389%2Fnext-mdx-video-blog%2Fhello-world_wwpzts&cloud_name=dpkreativ&player%5Bfluid%5D=true&player%5Bcontrols%5D=true&source%5Bsource_types%5D%5B0%5D=mp4" />\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    author: 'Key',
    comment_id_list: [],
    create_date: '2022-12-06',
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: 'a8e2fa8e-5a5c-4a3e-9a38-8b3a160f3e15',
    title: 'Example Post 4',
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['Game Design'],
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    author: 'Key',
    comment_id_list: [],
    create_date: '2022-12-06',
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: '4fca8134-1d33-4f97-b761-1089de3d3f13',
    title: 'Example Post 5',
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['Game Dev General', 'UE5'],
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    author: 'Key',
    comment_id_list: [],
    create_date: '2022-12-06',
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: 'c92bc4a3-4f34-45b1-b66f-e7c64fc8b39e',
    title: 'Example Post 31',
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['UE', 'Other'],
    content: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    author: 'Key',
    comment_id_list: [],
    create_date: '2022-12-06',
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "f7a9e3b7-8fd4-4b3f-bd7a-79a712f5f1a1",
    title: "Markdown Example Post",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['Game Design', 'UE5'],
    content: '## Example Post:\nProtecting user rights in the context of AI and data usage is a critical ethical issue...',
    author: 'Key',
    comment_id_list: [],
    create_date: "2023-01-15",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "9a2f4c51-7c2d-4b07-bd06-8fc6e6dbd1c9",
    title: "The Impact of Renewable Energy Technologies",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ["UE5", "Game Design", "UE / Blueprint"],
    content: "Renewable energy technologies likes solar and wind power are crucial in the transition to sustainable energy sources...",
    author: "Emma",
    comment_id_list: [],
    create_date: "2023-02-28",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "b0f4a1a8-9b67-4820-9cf3-25d7bcb6b1f5",
    title: "The Evolution of Robotics in Manufacturing",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / AI", "UE / Rendering", "Web Dev"],
    content: "Robotics technology is revolutionizing manufacturing processes, improving efficiency and precision...",
    author: "Sophia",
    comment_id_list: [],
    create_date: "2023-04-10",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "a7d5e0f2-38ef-4d02-bc11-1d332f9b5b49",
    title: "Artificial Intelligence in Autonomous Vehicles",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / Blueprint", "UE / Environment"],
    content: "AI plays a crucial role in the development of autonomous vehicles, enhancing safety and navigation capabilities...",
    author: "Daniel",
    comment_id_list: [],
    create_date: "2023-05-05",
    modify_date: '2022-12-06',
    likes: [],
  },
  // {
  //   id: "c3a7b1f9-cc8d-45b0-b7ac-9811e43c83b4",
  //   title: "The Promise of Quantum Computing",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["Quantum Computing", "Tech", "Future"],
  //   content: "Quantum computing holds immense potential to solve complex problems that are beyond the reach of classical computers...",
  //   author: "Olivia",
  //   comment_id_list: [],
  //   create_date: "2023-06-15",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "e2c6f5a0-8744-4b21-bd4a-9f06a458b03f",
  //   title: "Exploring Cybersecurity in the Age of IoT",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["Cybersecurity", "IoT", "Tech"],
  //   content: "As IoT devices proliferate, cybersecurity becomes increasingly crucial to protect data and ensure privacy...",
  //   author: "Liam",
  //   comment_id_list: [],
  //   create_date: "2023-07-20",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d8f9e2c3-64e2-42aa-96d1-8e47245ac5ae",
  //   title: "Augmented Reality: Bridging the Physical and Digital Worlds",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AR", "Tech", "Future"],
  //   content: "AR technology overlays digital information onto the physical world, transforming how we interact with our environment...",
  //   author: "Ava",
  //   comment_id_list: [],
  //   create_date: "2023-08-10",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "f1d8c4b5-5ef8-4327-b2e3-6f0bf2a1d7a7",
  //   title: "The Role of Blockchain in Supply Chain Management",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["Blockchain", "Supply Chain", "Tech"],
  //   content: "Blockchain enhances transparency and traceability in supply chains, reducing fraud and improving efficiency...",
  //   author: "Noah",
  //   comment_id_list: [],
  //   create_date: "2023-09-05",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "b6d5e8a3-ec75-4e7d-b62b-9e8e3c907a16",
  //   title: "The Future of 3D Printing Technology",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["3D Printing", "Tech", "Innovation"],
  //   content: "3D printing is revolutionizing manufacturing, healthcare, and even construction, enabling customized production...",
  //   author: "Ethan",
  //   comment_id_list: [],
  //   create_date: "2023-10-15",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "a9b8c7d6-e5f4-4a3b-8c2d-1f0e9b0d0a1b",
  //   title: "Advancements in Biotechnology: CRISPR and Beyond",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["Biotechnology", "CRISPR", "Tech"],
  //   content: "CRISPR technology allows precise genetic editing, revolutionizing agriculture, medicine, and biotechnology...",
  //   author: "Isabella",
  //   comment_id_list: [],
  //   create_date: "2023-11-20",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "f3e4d5c6-b7a8-4c9e-8d2f-0e1a2b3c4d5e",
  //   title: "Space Exploration: The Next Frontier",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["Space", "Tech", "Exploration"],
  //   content: "Advancements in space technology are enabling humanity to explore distant planets and understand the cosmos likes never before...",
  //   author: "Mia",
  //   comment_id_list: [],
  //   create_date: "2023-12-10",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f6a",
  //   title: "Ethical Considerations in AI Development",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Ethics", "Tech"],
  //   content: "As AI advances, ethical questions about bias, privacy, and accountability become increasingly important...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-05",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f6b",
  //   title: "1. AI and Privacy: Balancing Innovation with User Rights",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Privacy", "Tech"],
  //   content: "The rapid development of AI technologies raises significant concerns about user privacy...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-10",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f6c",
  //   title: "2. The Role of Transparency in AI Systems",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Transparency", "Tech"],
  //   content: "Transparency in AI is crucial for building trust and ensuring accountability...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-12",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f6d",
  //   title: "3. Bias in AI: Understanding and Mitigating Risks",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Bias", "Tech"],
  //   content: "Bias in AI systems can lead to unfair outcomes and reinforce existing inequalities...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-15",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f6e",
  //   title: "4. Ethical AI: Principles and Practices",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Ethics", "Tech"],
  //   content: "Implementing ethical principles in AI development is essential for responsible innovation...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-18",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f6f",
  //   title: "5. AI and Accountability: Who is Responsible?",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Accountability", "Tech"],
  //   content: "As AI systems become more autonomous, questions about accountability arise...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-20",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f70",
  //   title: "6. Privacy Concerns in the Age of AI",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Privacy", "Tech"],
  //   content: "The increasing use of AI technologies brings significant privacy concerns...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-22",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f71",
  //   title: "7. Building Trustworthy AI Systems",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Trust", "Tech"],
  //   content: "Trustworthiness is a key factor in the adoption and success of AI technologies...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-25",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f72",
  //   title: "8. AI and Human Rights: Ensuring Fair Treatment",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Human Rights", "Tech"],
  //   content: "AI systems must be designed to respect and uphold human rights...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-28",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f73",
  //   title: "9. Ethical Challenges in Autonomous AI",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Ethics", "Tech"],
  //   content: "Autonomous AI systems present unique ethical challenges that need careful consideration...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-01-30",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f74",
  //   title: "10. AI in Healthcare: Ethical Considerations",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Healthcare", "Tech"],
  //   content: "The use of AI in healthcare brings both opportunities and ethical dilemmas...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-02",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f75",
  //   title: "11. AI and Surveillance: Ethical Implications",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Surveillance", "Tech"],
  //   content: "The deployment of AI in surveillance raises critical ethical questions...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-05",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f76",
  //   title: "12. Algorithmic Bias: Causes and Solutions",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Bias", "Tech"],
  //   content: "Understanding and addressing the causes of algorithmic bias is crucial for fair AI...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-08",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f77",
  //   title: "13. AI and Job Displacement: Ethical Responses",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Employment", "Tech"],
  //   content: "The impact of AI on employment necessitates ethical considerations and responses...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-10",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f78",
  //   title: "14. Ethical AI: From Theory to Practice",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Ethics", "Tech"],
  //   content: "Translating ethical principles into practical AI applications is a complex but necessary task...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-13",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f79",
  //   title: "15. AI and the Future of Work: Ethical Perspectives",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Future of Work", "Tech"],
  //   content: "The future of work in the age of AI involves numerous ethical considerations...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-15",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f80",
  //   title: "16. AI and Data Ethics: Protecting User Rights",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Data Ethics", "Tech"],
  //   content: "Protecting user rights in the context of AI and data usage is a critical ethical issue...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-18",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f81",
  //   title: "17. Power of man: Protecting User Rights",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Data Ethics", "Tech"],
  //   content: "Protecting user rights in the context of AI and data usage is a critical ethical issue...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-18",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f82",
  //   title: "18. Power of man: Protecting User Rights",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Data Ethics", "Tech"],
  //   content: "Protecting user rights in the context of AI and data usage is a critical ethical issue...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-18",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f83",
  //   title: "19. Power of man: Protecting User Rights",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Data Ethics", "Tech"],
  //   content: "Protecting user rights in the context of AI and data usage is a critical ethical issue...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-18",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
  // {
  //   id: "d2e3f4a5-c6b7-4d8e-9f1a-0b2c3d4e5f84",
  //   title: "20. Power of man: Protecting User Rights",
  //   thumbnail_img: "/1920x1080_KirbyBday.png",
  //   tags: ["AI", "Data Ethics", "Tech"],
  //   content: "Protecting user rights in the context of AI and data usage is a critical ethical issue...",
  //   author: "Jacob",
  //   comment_id_list: [],
  //   create_date: "2024-02-18",
  //   modify_date: '2022-12-06',
  //   likes: 0,
  // },
];

const posts_ja = [
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442b",
    title: "例の投稿1",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE', 'Other'],
    content: "ロレム・イプサム・ドロール・シット・アメット、コンセクテトゥル・アディピシング・エリット・セッド・ド・エイウスモッド・テンポール・インシディドゥント・ウット・ラボーレ・エト・ドローレ・マグナ・アリカ。 ウト・エニム・アド・ミニム・ベニアム、クィス・ノストルド・エクサーシテイション・ウラムコ・ラボリス・ニシ・ウト・アリクィップ・エクス・エア・コモド・コンセクアット。",
    author: "Key",
    comment_id_list: ["3958dc9e-712f-4377-85e9-fec4b6a64420", "3958dc9e-712f-4377-85e9-fec4b6a64430"],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "86b93c2d-9d95-4c14-b05f-6e7e4e167c44",
    title: "例の投稿2",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Design', 'Game Dev General'],
    content: "# マークダウン  \n## マークダウン  \n### マークダウン  \n#### マークダウン  \n##### マークダウン  \n###### マークダウン  \n\n**太字**  \n*斜体*  \n~~取り消し線~~  \n\n1. 最初の項目  \n2. 2番目の項目  \n3. 3番目の項目  \n\n- 無順序の項目  \n- 無順序の項目  \n- 無順序の項目  \n\n[リンク](https://www.example.com)  \n\n![画像](https://cdn.vox-cdn.com/thumbor/6z9EcmyiAJ00A_eP5tk2DmVeYe0=/0x15:500x348/1200x800/filters:focal(0x15:500x348):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/36992002/tumblr_lmwsamrrxT1qagx30.0.0.gif) \n\n![画像](https://static.zenn.studio/images/drawing/discussion.png)  \n\n```javascript  \nconsole.log(\"Hello, World!\");  \n```  \n\n```cpp \nint main() { \n  int y = 5 + 6; \n cout << \"Hello World! \" << x << std::endl();\n} \n```  \n\n> 引用文  \n\n---  \n\n- [ ] タスク 1  \n- [x] タスク 2  \n\n---  \n\n| 見出し1 | 見出し2 |  \n| -------- | -------- |  \n| データ1   | データ2   |  \n\n---  \n\n<details>  \n<summary>詳細</summary>  \n詳細内容  \n</details>",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "e4189b55-9232-4e56-97ec-3d67bf7351d5",
    title: "例の投稿3",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE5', 'UE / Beginner'],
    content: "<video src=\"https://player.cloudinary.com/embed/?public_id=v1624176389%2Fnext-mdx-video-blog%2Fhello-world_wwpzts&cloud_name=dpkreativ&player%5Bfluid%5D=true&player%5Bcontrols%5D=true&source%5Bsource_types%5D%5B0%5D=mp4\" />\n\nロレム・イプサム・ドロール・シット・アメット、コンセクテトゥル・アディピシング・エリット・セッド・ド・エイウスモッド・テンポール・インシディドゥント・ウット・ラボーレ・エト・ドローレ・マグナ・アリカ。 ウト・エニム・アド・ミニム・ベニアム、クィス・ノストルド・エクサーシテイション・ウラムコ・ラボリス・ニシ・ウト・アリクィップ・エクス・エア・コモド・コンセクアット。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "a8e2fa8e-5a5c-4a3e-9a38-8b3a160f3e15",
    title: "例の投稿4",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Design'],
    content: "ロレム・イプサム・ドロール・シット・アメット、コンセクテトゥル・アディピシング・エリット・セッド・ド・エイウスモッド・テンポール・インシディドゥント・ウット・ラボーレ・エト・ドローレ・マグナ・アリカ。 ウト・エニム・アド・ミニム・ベニアム、クィス・ノストルド・エクサーシテイション・ウラムコ・ラボリス・ニシ・ウト・アリクィップ・エクス・エア・コモド・コンセクアット。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "4fca8134-1d33-4f97-b761-1089de3d3f13",
    title: "例の投稿5",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Dev General', 'UE5'],
    content: "ロレム・イプサム・ドロール・シット・アメット、コンセクテトゥル・アディピシング・エリット・セッド・ド・エイウスモッド・テンポール・インシディドゥント・ウット・ラボーレ・エト・ドローレ・マグナ・アリカ。 ウト・エニム・アド・ミニム・ベニアム、クィス・ノストルド・エクサーシテイション・ウラムコ・ラボリス・ニシ・ウト・アリクィップ・エクス・エア・コモド・コンセクアット。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "c92bc4a3-4f34-45b1-b66f-e7c64fc8b39e",
    title: "例の投稿31",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE', 'Other'],
    content: "ロレム・イプサム・ドロール・シット・アメット、コンセクテトゥル・アディピシング・エリット・セッド・ド・エイウスモッド・テンポール・インシディドゥント・ウット・ラボーレ・エト・ドローレ・マグナ・アリカ。 ウト・エニム・アド・ミニム・ベニアム、クィス・ノストルド・エクサーシテイション・ウラムコ・ラボリス・ニシ・ウト・アリクィップ・エクス・エア・コモド・コンセクアット。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: 0
  },
  {
    id: "f7a9e3b7-8fd4-4b3f-bd7a-79a712f5f1a1",
    title: "Markdownの例投稿",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['Game Design', 'UE5'],
    content: '## 例投稿:\nAIとデータ使用の文脈におけるユーザーの権利保護は、重要な倫理的問題です...111111111111111111111\n```cpp\nint32 largetNumber = 50;\nprivate:\nUPROPERTY(EditAnywhere)\nAActor* OsuCharacter;\n```\n> WWWE\n---\n~~***asdsa***~~\n## ASD\n### as\n# sTitle\n## Title\n![Wo_Long__Fallen_Dynasty_2023_07_09_13_29_31_kdkyvt](https://res.cloudinary.com/diy3s3seb/image/upload/v1721312231/Wo_Long__Fallen_Dynasty_2023_07_09_13_29_31_kdkyvt.png)\n- abc\n- edf\n- ddd\n- sdf\n- -\n-\n-\n-\n```ts:markdown.tsx:57-85\n&apos;use client&apos;;\nimport React, { Fragment, useState } from &apos;react&apos;;\nimport Markdown from &apos;react-markdown&apos;;\nimport remarkGfm from &apos;remark-gfm&apos;;\nimport rehypeRaw from &apos;rehype-raw&apos;;\nimport { Prism as SyntaxHighlighter } from &apos;react-syntax-highlighter&apos;;\nimport { oneDark } from &apos;react-syntax-highlighter/dist/cjs/styles/prism&apos;;\nimport CopyButton from &apos;../components/utils/copy&apos;;\nimport { escapeHtml } from &apos;../lib/escapeHtml&apos;;\ntype MarkdownRendererProps = {\nchildren: string;\n};\nconst customStyle = {\nfontSize: &apos;1rem&apos;;\npadding: &apos;20px&apos;;\n};\nexport function MarkdownRenderer({\nchildren: markdown,\n}: MarkdownRendererProps) {\nconst [showCopyToClipboard, setShowCopyToClipboard] = useState(false);\nreturn (\n<Markdown\nremarkPlugins={[remarkGfm]}\nrehypePlugins={[rehypeRaw]}\ncomponents={{\ncode({ node, inline, className, children, ...props }: any) {\nconst match = /language-(\w+)/.exec(className || &apos;&apos;);\nconst code = String(children).replace(/\n$/, &apos;&apos;);\nconst filename = match?.input.split(&apos;:&apos;)[1];\nconst linesToHighlightInput = match?.input.split(&apos;:&apos;)[2];\nconst linesToHighlight = linesToHighlightInput\n? linesToHighlightInput.split(&apos;,&apos;).reduce((acc, line) => {\nif (line.includes(&apos;-&apos;)) {\nconst [start, end] = line.split(&apos;-&apos;).map(Number);\nfor (let i = start; i <= end; i++) {\nacc.push(i);\n}\n} else {\nacc.push(Number(line));\n}\nreturn acc;\n}, [] as number[])\n: [];\nreturn !inline && match ? (\n<Fragment>\n{filename && (\n<div className=&apos;-mb-6 table max-w-full rounded-lg bg-slate-700 px-3 pb-4 pt-1 text-sm text-white&apos;>\n<span>{escapeHtml(filename)}</span>\n</div>\n)}\n<div\nclassName=&apos;relative&apos;\nonMouseEnter={() => setShowCopyToClipboard(true)}\nonMouseLeave={() => setShowCopyToClipboard(false)}\n>\n<SyntaxHighlighter\nstyle={oneDark}\ncustomStyle={customStyle}\nshowLineNumbers\nPreTag=&apos;div&apos;\nlanguage={match[1]}\nwrapLines\nlineProps={(lineNumber) => {\nconst style: any = {\ndisplay: &quot;block&quot;,\nwidth: &quot;fit-content&quot;,\n};\nif (linesToHighlight.includes(lineNumber)) {\nstyle.backgroundColor = &quot;#334155&quot;;\nstyle.borderColor = &quot;#38bdf8&quot;;\n}\nreturn { style };\n}}\n{...props}\n>\n{code}\n</SyntaxHighlighter>\n{showCopyToClipboard && <CopyButton copyContent={code} />}\n</div>\n</Fragment>\n) : (\n<code className={className} {...props}>\n{children}\n</code>\n);\n},\n}}\n>\n{markdown}\n</Markdown>\n);\n}\n```\n123\n<iframe width=&quot;1080&quot; height=&quot;720&quot; src=&quot;https://www.youtube.com/embed/gb7qXLnlaB4?si=mv_BGRqvSPjle3vd&quot; title=&quot;YouTube video player&quot; frameborder=&quot;0&quot; allow=&quot;accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share&quot; referrerpolicy=&quot;strict-origin-when-cross-origin&quot; allowfullscreen></iframe>\n<iframe border=0 frameborder=0 height=&quot;750&quot; width=&quot;550&quot;\nsrc=&quot;https://twitframe.com/show?url=https://twitter.com/Cerva_saiki/status/1812591071454699781?ref_src=twsrc%5Etfw&quot;></iframe>\n<iframe\nsrc=&quot;https://player.cloudinary.com/embed/?public_id=ThePathOfOsu_-_Unreal_Editor_2024-03-03_16-25-45_dlxws7&cloud_name=diy3s3seb&quot;\nwidth=&quot;640&quot;\nheight=&quot;360&quot;\nstyle=&quot;height: auto; width: 100%; aspect-ratio: 640 / 360;&quot;\nallow=&quot;autoplay; fullscreen; encrypted-media; picture-in-picture&quot;\nallowfullscreen\nframeborder=&quot;0&quot;\n></iframe>\n# Markdown\n## Markdown\n### Markdown\n#### Markdown\n##### Markdown\n###### Markdown\n**Bold**\n*Italic*\n~~Strikethrough~~\n1. First item\n2. Second item\n3. Third item\n- Unordered item\n- Unordered item\n- Unordered item\n[Link](https://www.example.com)\n![Image](https://cdn.vox-cdn.com/thumbor/6z9EcmyiAJ00A_eP5tk2DmVeYe0=/0x15:500x348/1200x800/filters:focal(0x15:500x348):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/36992002/tumblr_lmwsamrrxT1qagx30.0.0.gif)\n![Image](https://static.zenn.studio/images/drawing/discussion.png)\n```javascript\nconsole.log(&apos;Hello, World!&apos;);\n```\n```cpp\nint main() {\nint y = 5 + 6;\ncout &lt;&lt; &apos;Hellow World! &apos; &lt;&lt; x &lt;&lt; std::endl();\n}\n```\n> Blockquote\n---\n- [ ] Task 1\n- [x] Task 2\n---\n| Header 1 | Header 2 |\n| -------- | -------- |\n| Data 1   | Data 2   |\n---\n<details>\n<summary>Details</summary>\nDetails content\n</details>',
    author: 'Key',
    comment_id_list: [],
    create_date: "2023-01-15",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "9a2f4c51-7c2d-4b07-bd06-8fc6e6dbd1c9",
    title: "再生可能エネルギー技術の影響",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ["UE5", "Game Design", "UE / Blueprint"],
    content: "太陽光や風力などの再生可能エネルギー技術は、持続可能なエネルギー源への移行において重要です...",
    author: "Emma",
    comment_id_list: [],
    create_date: "2023-02-28",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "b0f4a1a8-9b67-4820-9cf3-25d7bcb6b1f5",
    title: "製造業におけるロボット工学の進化",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / AI", "UE / Rendering", "Web Dev"],
    content: "ロボット技術は製造プロセスを革新し、効率と精度を向上させています...",
    author: "Sophia",
    comment_id_list: [],
    create_date: "2023-04-10",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "a7d5e0f2-38ef-4d02-bc11-1d332f9b5b49",
    title: "自動運転車における人工知能",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / Blueprint", "UE / Environment"],
    content: "AIは自動運転車の開発において重要な役割を果たし、安全性とナビゲーション機能を強化しています...",
    author: "Daniel",
    comment_id_list: [],
    create_date: "2023-05-05",
    modify_date: '2022-12-06',
    likes: [],
  },
];

const posts_kr = [
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442b",
    title: "예제 게시물 1",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE', 'Other'],
    content: "로렘 입숨 돌로르 시트 아메트, 콘섹테투르 아디피싱 엘리트, 세드 도 에이우스모드 템포르 인시디둔트 우트 라보레 에트 돌로레 마그나 알리쿠아. 우트 에님 아드 미님 베니암, 퀴스 노스트루드 엑서시테이션 울람코 라보리스 니시 우트 알리큅 엑스 에아 코모도 콘세콰트.",
    author: "Key",
    comment_id_list: ["3958dc9e-712f-4377-85e9-fec4b6a64420", "3958dc9e-712f-4377-85e9-fec4b6a64430"],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "86b93c2d-9d95-4c14-b05f-6e7e4e167c44",
    title: "예제 게시물 2",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Design', 'Game Dev General'],
    content: "# 마크다운  \n## 마크다운  \n### 마크다운  \n#### 마크다운  \n##### 마크다운  \n###### 마크다운  \n\n**굵게**  \n*이탤릭체*  \n~~취소선~~  \n\n1. 첫 번째 항목  \n2. 두 번째 항목  \n3. 세 번째 항목  \n\n- 순서 없는 항목  \n- 순서 없는 항목  \n- 순서 없는 항목  \n\n[링크](https://www.example.com)  \n\n![이미지](https://cdn.vox-cdn.com/thumbor/6z9EcmyiAJ00A_eP5tk2DmVeYe0=/0x15:500x348/1200x800/filters:focal(0x15:500x348):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/36992002/tumblr_lmwsamrrxT1qagx30.0.0.gif) \n\n![이미지](https://static.zenn.studio/images/drawing/discussion.png)  \n\n```javascript  \nconsole.log(\"Hello, World!\");  \n```  \n\n```cpp \nint main() { \n  int y = 5 + 6; \n cout << \"Hello World! \" << x << std::endl();\n} \n```  \n\n> 인용문  \n\n---  \n\n- [ ] 작업 1  \n- [x] 작업 2  \n\n---  \n\n| 헤더 1 | 헤더 2 |  \n| -------- | -------- |  \n| 데이터 1   | 데이터 2   |  \n\n---  \n\n<details>  \n<summary>세부사항</summary>  \n세부사항 내용  \n</details>",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "e4189b55-9232-4e56-97ec-3d67bf7351d5",
    title: "예제 게시물 3",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE5', 'UE / Beginner'],
    content: "<video src=\"https://player.cloudinary.com/embed/?public_id=v1624176389%2Fnext-mdx-video-blog%2Fhello-world_wwpzts&cloud_name=dpkreativ&player%5Bfluid%5D=true&player%5Bcontrols%5D=true&source%5Bsource_types%5D%5B0%5D=mp4\" />\n\n로렘 입숨 돌로르 시트 아메트, 콘섹테투르 아디피싱 엘리트, 세드 도 에이우스모드 템포르 인시디둔트 우트 라보레 에트 돌로레 마그나 알리쿠아. 우트 에님 아드 미님 베니암, 퀴스 노스트루드 엑서시테이션 울람코 라보리스 니시 우트 알리큅 엑스 에아 코모도 콘세콰트.",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "a8e2fa8e-5a5c-4a3e-9a38-8b3a160f3e15",
    title: "예제 게시물 4",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Design'],
    content: "로렘 입숨 돌로르 시트 아메트, 콘섹테투르 아디피싱 엘리트, 세드 도 에이우스모드 템포르 인시디둔트 우트 라보레 에트 돌로레 마그나 알리쿠아. 우트 에님 아드 미님 베니암, 퀴스 노스트루드 엑서시테이션 울람코 라보리스 니시 우트 알리큅 엑스 에아 코모도 콘세콰트.",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "4fca8134-1d33-4f97-b761-1089de3d3f13",
    title: "예제 게시물 5",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Dev General', 'UE5'],
    content: "로렘 입숨 돌로르 시트 아메트, 콘섹테투르 아디피싱 엘리트, 세드 도 에이우스모드 템포르 인시디둔트 우트 라보레 에트 돌로레 마그나 알리쿠아. 우트 에님 아드 미님 베니암, 퀴스 노스트루드 엑서시테이션 울람코 라보리스 니시 우트 알리큅 엑스 에아 코모도 콘세콰트.",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "c92bc4a3-4f34-45b1-b66f-e7c64fc8b39e",
    title: "예제 게시물 31",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE', 'Other'],
    content: "로렘 입숨 돌로르 시트 아메트, 콘섹테투르 아디피싱 엘리트, 세드 도 에이우스모드 템포르 인시디둔트 우트 라보레 에트 돌로레 마그나 알리쿠아. 우트 에님 아드 미님 베니암, 퀴스 노스트루드 엑서시테이션 울람코 라보리스 니시 우트 알리큅 엑스 에아 코모도 콘세콰트.",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "f7a9e3b7-8fd4-4b3f-bd7a-79a712f5f1a1",
    title: "Markdown 예시 게시물",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['Game Design', 'UE5'],
    content: '## 예제 게시물:\nAI와 데이터 사용의 맥락에서 사용자 권리 보호는 중요한 윤리적 문제입니다...111111111111111111111\n```cpp\nint32 largetNumber = 50;\nprivate:\nUPROPERTY(EditAnywhere)\nAActor* OsuCharacter;\n```\n> WWWE\n---\n~~***asdsa***~~\n## ASD\n### as\n# sTitle\n## Title\n![Wo_Long__Fallen_Dynasty_2023_07_09_13_29_31_kdkyvt](https://res.cloudinary.com/diy3s3seb/image/upload/v1721312231/Wo_Long__Fallen_Dynasty_2023_07_09_13_29_31_kdkyvt.png)\n- abc\n- edf\n- ddd\n- sdf\n- -\n-\n-\n-\n```ts:markdown.tsx:57-85\n&apos;use client&apos;;\nimport React, { Fragment, useState } from &apos;react&apos;;\nimport Markdown from &apos;react-markdown&apos;;\nimport remarkGfm from &apos;remark-gfm&apos;;\nimport rehypeRaw from &apos;rehype-raw&apos;;\nimport { Prism as SyntaxHighlighter } from &apos;react-syntax-highlighter&apos;;\nimport { oneDark } from &apos;react-syntax-highlighter/dist/cjs/styles/prism&apos;;\nimport CopyButton from &apos;../components/utils/copy&apos;;\nimport { escapeHtml } from &apos;../lib/escapeHtml&apos;;\ntype MarkdownRendererProps = {\nchildren: string;\n};\nconst customStyle = {\nfontSize: &apos;1rem&apos;;\npadding: &apos;20px&apos;;\n};\nexport function MarkdownRenderer({\nchildren: markdown,\n}: MarkdownRendererProps) {\nconst [showCopyToClipboard, setShowCopyToClipboard] = useState(false);\nreturn (\n<Markdown\nremarkPlugins={[remarkGfm]}\nrehypePlugins={[rehypeRaw]}\ncomponents={{\ncode({ node, inline, className, children, ...props }: any) {\nconst match = /language-(\w+)/.exec(className || &apos;&apos;);\nconst code = String(children).replace(/\n$/, &apos;&apos;);\nconst filename = match?.input.split(&apos;:&apos;)[1];\nconst linesToHighlightInput = match?.input.split(&apos;:&apos;)[2];\nconst linesToHighlight = linesToHighlightInput\n? linesToHighlightInput.split(&apos;,&apos;).reduce((acc, line) => {\nif (line.includes(&apos;-&apos;)) {\nconst [start, end] = line.split(&apos;-&apos;).map(Number);\nfor (let i = start; i <= end; i++) {\nacc.push(i);\n}\n} else {\nacc.push(Number(line));\n}\nreturn acc;\n}, [] as number[])\n: [];\nreturn !inline && match ? (\n<Fragment>\n{filename && (\n<div className=&apos;-mb-6 table max-w-full rounded-lg bg-slate-700 px-3 pb-4 pt-1 text-sm text-white&apos;>\n<span>{escapeHtml(filename)}</span>\n</div>\n)}\n<div\nclassName=&apos;relative&apos;\nonMouseEnter={() => setShowCopyToClipboard(true)}\nonMouseLeave={() => setShowCopyToClipboard(false)}\n>\n<SyntaxHighlighter\nstyle={oneDark}\ncustomStyle={customStyle}\nshowLineNumbers\nPreTag=&apos;div&apos;\nlanguage={match[1]}\nwrapLines\nlineProps={(lineNumber) => {\nconst style: any = {\ndisplay: &quot;block&quot;,\nwidth: &quot;fit-content&quot;,\n};\nif (linesToHighlight.includes(lineNumber)) {\nstyle.backgroundColor = &quot;#334155&quot;;\nstyle.borderColor = &quot;#38bdf8&quot;;\n}\nreturn { style };\n}}\n{...props}\n>\n{code}\n</SyntaxHighlighter>\n{showCopyToClipboard && <CopyButton copyContent={code} />}\n</div>\n</Fragment>\n) : (\n<code className={className} {...props}>\n{children}\n</code>\n);\n},\n}}\n>\n{markdown}\n</Markdown>\n);\n}\n```\n123\n<iframe width=&quot;1080&quot; height=&quot;720&quot; src=&quot;https://www.youtube.com/embed/gb7qXLnlaB4?si=mv_BGRqvSPjle3vd&quot; title=&quot;YouTube video player&quot; frameborder=&quot;0&quot; allow=&quot;accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share&quot; referrerpolicy=&quot;strict-origin-when-cross-origin&quot; allowfullscreen></iframe>\n<iframe border=0 frameborder=0 height=&quot;750&quot; width=&quot;550&quot;\nsrc=&quot;https://twitframe.com/show?url=https://twitter.com/Cerva_saiki/status/1812591071454699781?ref_src=twsrc%5Etfw&quot;></iframe>\n<iframe\nsrc=&quot;https://player.cloudinary.com/embed/?public_id=ThePathOfOsu_-_Unreal_Editor_2024-03-03_16-25-45_dlxws7&cloud_name=diy3s3seb&quot;\nwidth=&quot;640&quot;\nheight=&quot;360&quot;\nstyle=&quot;height: auto; width: 100%; aspect-ratio: 640 / 360;&quot;\nallow=&quot;autoplay; fullscreen; encrypted-media; picture-in-picture&quot;\nallowfullscreen\nframeborder=&quot;0&quot;\n></iframe>\n# Markdown\n## Markdown\n### Markdown\n#### Markdown\n##### Markdown\n###### Markdown\n**Bold**\n*Italic*\n~~Strikethrough~~\n1. First item\n2. Second item\n3. Third item\n- Unordered item\n- Unordered item\n- Unordered item\n[Link](https://www.example.com)\n![Image](https://cdn.vox-cdn.com/thumbor/6z9EcmyiAJ00A_eP5tk2DmVeYe0=/0x15:500x348/1200x800/filters:focal(0x15:500x348):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/36992002/tumblr_lmwsamrrxT1qagx30.0.0.gif)\n![Image](https://static.zenn.studio/images/drawing/discussion.png)\n```javascript\nconsole.log(&apos;Hello, World!&apos;);\n```\n```cpp\nint main() {\nint y = 5 + 6;\ncout &lt;&lt; &apos;Hellow World! &apos; &lt;&lt; x &lt;&lt; std::endl();\n}\n```\n> Blockquote\n---\n- [ ] Task 1\n- [x] Task 2\n---\n| Header 1 | Header 2 |\n| -------- | -------- |\n| Data 1   | Data 2   |\n---\n<details>\n<summary>Details</summary>\nDetails content\n</details>',
    author: 'Key',
    comment_id_list: [],
    create_date: "2023-01-15",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "9a2f4c51-7c2d-4b07-bd06-8fc6e6dbd1c9",
    title: "재생 가능 에너지 기술의 영향",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ["UE5", "Game Design", "UE / Blueprint"],
    content: "태양광 및 풍력과 같은 재생 가능 에너지 기술은 지속 가능한 에너지 자원으로의 전환에 중요합니다...",
    author: "Emma",
    comment_id_list: [],
    create_date: "2023-02-28",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "b0f4a1a8-9b67-4820-9cf3-25d7bcb6b1f5",
    title: "제조업에서의 로봇 공학의 진화",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / AI", "UE / Rendering", "Web Dev"],
    content: "로봇 기술은 제조 프로세스를 혁신하고 효율성과 정밀성을 향상시키고 있습니다...",
    author: "Sophia",
    comment_id_list: [],
    create_date: "2023-04-10",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "a7d5e0f2-38ef-4d02-bc11-1d332f9b5b49",
    title: "자율 주행 차량에서의 인공지능",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / Blueprint", "UE / Environment"],
    content: "AI는 자율 주행 차량 개발에서 중요한 역할을 하며 안전성과 내비게이션 기능을 강화합니다...",
    author: "Daniel",
    comment_id_list: [],
    create_date: "2023-05-05",
    modify_date: '2022-12-06',
    likes: [],
  },
];

const posts_hk = [
  {
    id: "3958dc9e-712f-4377-85e9-fec4b6a6442b",
    title: "範例帖子 1",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE', 'Other'],
    content: "羅倫·伊普森·多洛·西特·阿梅特，貢塞特圖爾·阿迪皮斯辛·艾利特，塞德·多·埃伊烏斯莫德·坦普爾·因西迪杜恩特·烏特·拉博雷·埃特·多洛雷·馬格納·阿利夸。烏特·埃尼姆·阿德·米尼姆·韋尼亞姆，奎斯·諾斯特魯德·埃克塞西塔西翁·烏拉姆科·拉博里斯·尼斯烏特·阿利奎普·埃克斯·埃亞·科莫多·康塞庫阿特。",
    author: "Key",
    comment_id_list: ["3958dc9e-712f-4377-85e9-fec4b6a64420", "3958dc9e-712f-4377-85e9-fec4b6a64430"],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "86b93c2d-9d95-4c14-b05f-6e7e4e167c44",
    title: "範例帖子 2",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Design', 'Game Dev General'],
    content: "# Markdown  \n## Markdown  \n### Markdown  \n#### Markdown  \n##### Markdown  \n###### Markdown  \n\n**粗體**  \n*斜體*  \n~~刪除線~~  \n\n1. 第一項  \n2. 第二項  \n3. 第三項  \n\n- 無序項目  \n- 無序項目  \n- 無序項目  \n\n[連結](https://www.example.com)  \n\n![圖像](https://cdn.vox-cdn.com/thumbor/6z9EcmyiAJ00A_eP5tk2DmVeYe0=/0x15:500x348/1200x800/filters:focal(0x15:500x348):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/36992002/tumblr_lmwsamrrxT1qagx30.0.0.gif) \n\n![圖像](https://static.zenn.studio/images/drawing/discussion.png)  \n\n```javascript  \nconsole.log(\"Hello, World!\");  \n```  \n\n```cpp \nint main() { \n  int y = 5 + 6; \n cout << \"Hello World! \" << x << std::endl();\n} \n```  \n\n> 引述  \n\n---  \n\n- [ ] 任務 1  \n- [x] 任務 2  \n\n---  \n\n| 標題 1 | 標題 2 |  \n| -------- | -------- |  \n| 資料 1   | 資料 2   |  \n\n---  \n\n<details>  \n<summary>詳細信息</summary>  \n詳細信息內容  \n</details>",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "e4189b55-9232-4e56-97ec-3d67bf7351d5",
    title: "範例帖子 3",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE5', 'UE / Beginner'],
    content: "<video src=\"https://player.cloudinary.com/embed/?public_id=v1624176389%2Fnext-mdx-video-blog%2Fhello-world_wwpzts&cloud_name=dpkreativ&player%5Bfluid%5D=true&player%5Bcontrols%5D=true&source%5Bsource_types%5D%5B0%5D=mp4\" />\n\n羅倫·伊普森·多洛·西特·阿梅特，貢塞特圖爾·阿迪皮斯辛·艾利特，塞德·多·埃伊烏斯莫德·坦普爾·因西迪杜恩特·烏特·拉博雷·埃特·多洛雷·馬格納·阿利夸。烏特·埃尼姆·阿德·米尼姆·韋尼亞姆，奎斯·諾斯特魯德·埃克塞西塔西翁·烏拉姆科·拉博里斯·尼斯烏特·阿利奎普·埃克斯·埃亞·科莫多·康塞庫阿特。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "a8e2fa8e-5a5c-4a3e-9a38-8b3a160f3e15",
    title: "範例帖子 4",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Design'],
    content: "羅倫·伊普森·多洛·西特·阿梅特，貢塞特圖爾·阿迪皮斯辛·艾利特，塞德·多·埃伊烏斯莫德·坦普爾·因西迪杜恩特·烏特·拉博雷·埃特·多洛雷·馬格納·阿利夸。烏特·埃尼姆·阿德·米尼姆·韋尼亞姆，奎斯·諾斯特魯德·埃克塞西塔西翁·烏拉姆科·拉博里斯·尼斯烏特·阿利奎普·埃克斯·埃亞·科莫多·康塞庫阿特。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "4fca8134-1d33-4f97-b761-1089de3d3f13",
    title: "範例帖子 5",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['Game Dev General', 'UE5'],
    content: "羅倫·伊普森·多洛·西特·阿梅特，貢塞特圖爾·阿迪皮斯辛·艾利特，塞德·多·埃伊烏斯莫德·坦普爾·因西迪杜恩特·烏特·拉博雷·埃特·多洛雷·馬格納·阿利夸。烏特·埃尼姆·阿德·米尼姆·韋尼亞姆，奎斯·諾斯特魯德·埃克塞西塔西翁·烏拉姆科·拉博里斯·尼斯烏特·阿利奎普·埃克斯·埃亞·科莫多·康塞庫阿特。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "c92bc4a3-4f34-45b1-b66f-e7c64fc8b39e",
    title: "範例帖子 31",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ['UE', 'Other'],
    content: "羅倫·伊普森·多洛·西特·阿梅特，貢塞特圖爾·阿迪皮斯辛·艾利特，塞德·多·埃伊烏斯莫德·坦普爾·因西迪杜恩特·烏特·拉博雷·埃特·多洛雷·馬格納·阿利夸。烏特·埃尼姆·阿德·米尼姆·韋尼亞姆，奎斯·諾斯特魯德·埃克塞西塔西翁·烏拉姆科·拉博里斯·尼斯烏特·阿利奎普·埃克斯·埃亞·科莫多·康塞庫阿特。",
    author: "Key",
    comment_id_list: [],
    create_date: "2022-12-06",
    modify_date: "2022-12-06",
    likes: [],
  },
  {
    id: "f7a9e3b7-8fd4-4b3f-bd7a-79a712f5f1a1",
    title: "Markdown 示例帖子",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ['Game Design', 'UE5'],
    content: '## 範例帖子:\n在AI和數據使用的背景下，保護用戶權利是一個重要的倫理問題...111111111111111111111\n```cpp\nint32 largetNumber = 50;\nprivate:\nUPROPERTY(EditAnywhere)\nAActor* OsuCharacter;\n```\n> WWWE\n---\n~~***asdsa***~~\n## ASD\n### as\n# sTitle\n## Title\n![Wo_Long__Fallen_Dynasty_2023_07_09_13_29_31_kdkyvt](https://res.cloudinary.com/diy3s3seb/image/upload/v1721312231/Wo_Long__Fallen_Dynasty_2023_07_09_13_29_31_kdkyvt.png)\n- abc\n- edf\n- ddd\n- sdf\n- -\n-\n-\n-\n```ts:markdown.tsx:57-85\n&apos;use client&apos;;\nimport React, { Fragment, useState } from &apos;react&apos;;\nimport Markdown from &apos;react-markdown&apos;;\nimport remarkGfm from &apos;remark-gfm&apos;;\nimport rehypeRaw from &apos;rehype-raw&apos;;\nimport { Prism as SyntaxHighlighter } from &apos;react-syntax-highlighter&apos;;\nimport { oneDark } from &apos;react-syntax-highlighter/dist/cjs/styles/prism&apos;;\nimport CopyButton from &apos;../components/utils/copy&apos;;\nimport { escapeHtml } from &apos;../lib/escapeHtml&apos;;\ntype MarkdownRendererProps = {\nchildren: string;\n};\nconst customStyle = {\nfontSize: &apos;1rem&apos;;\npadding: &apos;20px&apos;;\n};\nexport function MarkdownRenderer({\nchildren: markdown,\n}: MarkdownRendererProps) {\nconst [showCopyToClipboard, setShowCopyToClipboard] = useState(false);\nreturn (\n<Markdown\nremarkPlugins={[remarkGfm]}\nrehypePlugins={[rehypeRaw]}\ncomponents={{\ncode({ node, inline, className, children, ...props }: any) {\nconst match = /language-(\w+)/.exec(className || &apos;&apos;);\nconst code = String(children).replace(/\n$/, &apos;&apos;);\nconst filename = match?.input.split(&apos;:&apos;)[1];\nconst linesToHighlightInput = match?.input.split(&apos;:&apos;)[2];\nconst linesToHighlight = linesToHighlightInput\n? linesToHighlightInput.split(&apos;,&apos;).reduce((acc, line) => {\nif (line.includes(&apos;-&apos;)) {\nconst [start, end] = line.split(&apos;-&apos;).map(Number);\nfor (let i = start; i <= end; i++) {\nacc.push(i);\n}\n} else {\nacc.push(Number(line));\n}\nreturn acc;\n}, [] as number[])\n: [];\nreturn !inline && match ? (\n<Fragment>\n{filename && (\n<div className=&apos;-mb-6 table max-w-full rounded-lg bg-slate-700 px-3 pb-4 pt-1 text-sm text-white&apos;>\n<span>{escapeHtml(filename)}</span>\n</div>\n)}\n<div\nclassName=&apos;relative&apos;\nonMouseEnter={() => setShowCopyToClipboard(true)}\nonMouseLeave={() => setShowCopyToClipboard(false)}\n>\n<SyntaxHighlighter\nstyle={oneDark}\ncustomStyle={customStyle}\nshowLineNumbers\nPreTag=&apos;div&apos;\nlanguage={match[1]}\nwrapLines\nlineProps={(lineNumber) => {\nconst style: any = {\ndisplay: &quot;block&quot;,\nwidth: &quot;fit-content&quot;,\n};\nif (linesToHighlight.includes(lineNumber)) {\nstyle.backgroundColor = &quot;#334155&quot;;\nstyle.borderColor = &quot;#38bdf8&quot;;\n}\nreturn { style };\n}}\n{...props}\n>\n{code}\n</SyntaxHighlighter>\n{showCopyToClipboard && <CopyButton copyContent={code} />}\n</div>\n</Fragment>\n) : (\n<code className={className} {...props}>\n{children}\n</code>\n);\n},\n}}\n>\n{markdown}\n</Markdown>\n);\n}\n```\n123\n<iframe width=&quot;1080&quot; height=&quot;720&quot; src=&quot;https://www.youtube.com/embed/gb7qXLnlaB4?si=mv_BGRqvSPjle3vd&quot; title=&quot;YouTube video player&quot; frameborder=&quot;0&quot; allow=&quot;accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share&quot; referrerpolicy=&quot;strict-origin-when-cross-origin&quot; allowfullscreen></iframe>\n<iframe border=0 frameborder=0 height=&quot;750&quot; width=&quot;550&quot;\nsrc=&quot;https://twitframe.com/show?url=https://twitter.com/Cerva_saiki/status/1812591071454699781?ref_src=twsrc%5Etfw&quot;></iframe>\n<iframe\nsrc=&quot;https://player.cloudinary.com/embed/?public_id=ThePathOfOsu_-_Unreal_Editor_2024-03-03_16-25-45_dlxws7&cloud_name=diy3s3seb&quot;\nwidth=&quot;640&quot;\nheight=&quot;360&quot;\nstyle=&quot;height: auto; width: 100%; aspect-ratio: 640 / 360;&quot;\nallow=&quot;autoplay; fullscreen; encrypted-media; picture-in-picture&quot;\nallowfullscreen\nframeborder=&quot;0&quot;\n></iframe>\n# Markdown\n## Markdown\n### Markdown\n#### Markdown\n##### Markdown\n###### Markdown\n**Bold**\n*Italic*\n~~Strikethrough~~\n1. First item\n2. Second item\n3. Third item\n- Unordered item\n- Unordered item\n- Unordered item\n[Link](https://www.example.com)\n![Image](https://cdn.vox-cdn.com/thumbor/6z9EcmyiAJ00A_eP5tk2DmVeYe0=/0x15:500x348/1200x800/filters:focal(0x15:500x348):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/36992002/tumblr_lmwsamrrxT1qagx30.0.0.gif)\n![Image](https://static.zenn.studio/images/drawing/discussion.png)\n```javascript\nconsole.log(&apos;Hello, World!&apos;);\n```\n```cpp\nint main() {\nint y = 5 + 6;\ncout &lt;&lt; &apos;Hellow World! &apos; &lt;&lt; x &lt;&lt; std::endl();\n}\n```\n> Blockquote\n---\n- [ ] Task 1\n- [x] Task 2\n---\n| Header 1 | Header 2 |\n| -------- | -------- |\n| Data 1   | Data 2   |\n---\n<details>\n<summary>Details</summary>\nDetails content\n</details>',
    author: 'Key',
    comment_id_list: [],
    create_date: "2023-01-15",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "9a2f4c51-7c2d-4b07-bd06-8fc6e6dbd1c9",
    title: "可再生能源技術的影響",
    thumbnail_img: '/1920x1080_KirbyBday.png',
    tags: ["UE5", "Game Design", "UE / Blueprint"],
    content: "太陽能和風能等可再生能源技術對於向可持續能源來源的轉變至關重要...",
    author: "Emma",
    comment_id_list: [],
    create_date: "2023-02-28",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "b0f4a1a8-9b67-4820-9cf3-25d7bcb6b1f5",
    title: "製造業中的機器人技術演變",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / AI", "UE / Rendering", "Web Dev"],
    content: "機器人技術正在革新製造流程，提高效率和精度...",
    author: "Sophia",
    comment_id_list: [],
    create_date: "2023-04-10",
    modify_date: '2022-12-06',
    likes: [],
  },
  {
    id: "a7d5e0f2-38ef-4d02-bc11-1d332f9b5b49",
    title: "自動駕駛車輛中的人工智能",
    thumbnail_img: "/1920x1080_KirbyBday.png",
    tags: ["UE / Blueprint", "UE / Environment"],
    content: "AI 在自動駕駛車輛的開發中起著至關重要的作用，增強了安全性和導航能力...",
    author: "Daniel",
    comment_id_list: [],
    create_date: "2023-05-05",
    modify_date: '2022-12-06',
    likes: [],
  },
];

module.exports = {
  users,
  post_tags,
  posts_en,
  posts_ja,
  posts_kr,
  posts_hk,
  comments,
  notifications,
};
